"""empty message

Revision ID: 11578f2a6f09
Revises: 93384bdb9cc1
Create Date: 2024-04-26 03:04:40.303497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11578f2a6f09'
down_revision = '93384bdb9cc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')

    # ### end Alembic commands ###
